--------------------------------------------------------
--  DDL for View DIM_TIJDBLOK_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PIMS"."DIM_TIJDBLOK_V" ("TOTAL_DESCRIPTION", "TOTAL_ID", "TOTAL_CODE", "H_START_TIME", "HOURS_ID", "H_HOUR", "H_END_TIME", "HOURS_CODE", "HOURS_DESCRIPTION", "QUARTERS_DESCRIPTION", "Q_START_TIME", "QUARTERS_CODE", "QUARTERS_ID", "Q_END_TIME", "Q_QUARTER", "ID", "DATE_CREATED", "DATE_UPDATED", "DATE_DELETED", "AUD_ID_CREATED", "AUD_ID_UPDATED", "AUD_ID_DELETED", "CURR_ID") AS 
  select "TOTAL_DESCRIPTION","TOTAL_ID","TOTAL_CODE","H_START_TIME","HOURS_ID","H_HOUR","H_END_TIME","HOURS_CODE","HOURS_DESCRIPTION","QUARTERS_DESCRIPTION","Q_START_TIME","QUARTERS_CODE","QUARTERS_ID","Q_END_TIME","Q_QUARTER","ID","DATE_CREATED","DATE_UPDATED","DATE_DELETED","AUD_ID_CREATED","AUD_ID_UPDATED","AUD_ID_DELETED","CURR_ID" from ODS_HLP_TIJDBLOK_H where curr_id = 'Y' 

;
