--------------------------------------------------------
--  DDL for View DIM_BOOKING_DURATIONS_V
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PIMS"."DIM_BOOKING_DURATIONS_V" ("DIMENSION_KEY", "TOTAL_ID", "TOTAL_CODE", "TOTAL_DESCRIPTION", "TOTAL_DURATION", "WEEKS_ID", "WEEKS_CODE", "WEEKS_DESCRIPTION", "WEEKS_DURATION", "DAYS_ID", "DAYS_CODE", "DAYS_DESCRIPTION", "DAYS_DURATION", "HOURS_ID", "HOURS_CODE", "HOURS_DESCRIPTION", "HOURS_DURATION", "QUARTERS_ID", "QUARTERS_CODE", "QUARTERS_DESCRIPTION", "QUARTERS_DURATION", "SHORT_PARK_ID", "SHORT_PARK_CODE", "SHORT_PARK_DESCRIPTION", "LONG_PARK_ID", "LONG_PARK_CODE", "LONG_PARK_DESCRIPTION", "DURATION_LOW_VALUE", "DURATION_HIGH_VALUE", "ODS_ID") AS 
  select "DIMENSION_KEY","TOTAL_ID","TOTAL_CODE","TOTAL_DESCRIPTION","TOTAL_DURATION","WEEKS_ID","WEEKS_CODE","WEEKS_DESCRIPTION","WEEKS_DURATION","DAYS_ID","DAYS_CODE","DAYS_DESCRIPTION","DAYS_DURATION","HOURS_ID","HOURS_CODE","HOURS_DESCRIPTION","HOURS_DURATION","QUARTERS_ID","QUARTERS_CODE","QUARTERS_DESCRIPTION","QUARTERS_DURATION","SHORT_PARK_ID","SHORT_PARK_CODE","SHORT_PARK_DESCRIPTION","LONG_PARK_ID","LONG_PARK_CODE","LONG_PARK_DESCRIPTION","DURATION_LOW_VALUE","DURATION_HIGH_VALUE","ODS_ID" from pims_user.PIMS_MRT_BOOKING_DURATIONS 

;
